### ISSUE TITLE
akamai-cps script missing python preamble

### ISSUE THREAD

**Issue by rajiv** [akamai/cli-cps#1]
the `akamai-cps` script should have this line at the top of the script:

```
#!/usr/bin/env python3
```

this is needed as on many systems the `python` binary is python 2.x, and this script requires python 3.x. see https://www.python.org/dev/peps/pep-0394/ for details.

**Comment by vreddhi** [comment]
@rajiv and @aetsai 

1. Shouldn't this line be part of the core CLI script that invokes the `akamai-cps` python script?
2. Also, the user might have installed python3 in a custom location, and if that is the case. I see the below recommendation as well.
`When reinvoking the interpreter from a Python script, querying sys.executable to avoid hardcoded assumptions regarding the interpreter location remains the preferred approach.`
