### ISSUE TITLE
jsonpatch not in requirements.txt

### ISSUE THREAD

**Issue by ericdebeij** [akamai/cli-cps#11]
akamai cps list
Traceback (most recent call last):
  File "/Users/hdebeij/.akamai-cli/src/cli-cps/bin/akamai-cps", line 35, in <module>
    import jsonpatch
ModuleNotFoundError: No module named 'jsonpatch'

Reason is that the requirements.txt does not contain the reference

**Comment by vreddhi** [comment]
Can you please upgrade the cps package using akamai cps upgrade and test it again? We no more use jsonpatch, and hence i just updated the code too as part of latest release v1.0.0.

**Comment by ericdebeij** [comment]
Thanks. Akamai cps upgrade did not work, but akamai update cps did.
