### ISSUE TITLE
can not install to mac

### ISSUE THREAD

**Issue by kentaro0919** [akamai/cli-cps#14]
When I try to install to mac, it was not running.

```
$ akamai install  cps
Attempting to fetch command from https://github.com/akamai/cli-cps.git...... [OK]
Installing...... [FAIL]
Unable to run package manager: exit status 1
```

**Comment by vreddhi** [comment]
CPS for CLI requires python 3. I hope you have it installed. I suggest the following steps:

1. Install pyenv `brew install pyenv`
2. Install python3 into it `pyenv install 3.6.1`
3. execute `pyenv local 3.6.1`

Now you are all set to install CPS for CLI into the pyenv you just created. So execute `akamai install cps`

**Comment by aetsai** [comment]
There is also a new CLI version (binary) 1.1.0 that should give more logging for what is happening with the install.

https://github.com/akamai/cli/releases

**Comment by aetsai** [comment]
Also ran into an issue with python3.7 with pyyaml, just updated requirements.txt

**Comment by vreddhi** [comment]
@kentaro0919 closing this issue for now. You may re-open it if in case you still are not able to install it.
