### ISSUE TITLE
env var AKAMAI_EDGERC_SECTION being ignored

### ISSUE THREAD

**Issue by RafPe** [akamai/cli-cps#19]
**Problem**: 
CPS cli does not take under consideration the env variable and prompts for section

**Command run**:
`akamai cps retrieve-deployed --enrollment-id 6789 --info`

**Expected**: 
Results of command
**Was**:  
`Edgerc section "cps" not found`

> System info
```
[root@b4a42ffb5973 /]# akamai cps --version
akamai cps 0.1.0

[root@b4a42ffb5973 /]# echo $AKAMAI_EDGERC_SECTION
mySection
```

**Comment by lkowalsk-akamai-com** [comment]
Superseded by https://github.com/akamai/cli-cps/issues/48, hence closing
