### ISSUE TITLE
Enable option to create Certificates with same CN 

### ISSUE THREAD

**Issue by santosh-akamai** [akamai/cli-cps#22]
The CPI API allows the user to create a certificate with same CN. In order, to do the same in CLI the cpsAPIWraper.py has to be updated to include '&allow-duplicate-cn=true' argument for create_enrollment_url. The example of the required action is below.

From:
        create_enrollment_url = 'https://' + self.access_hostname + \
            '/cps/v2/enrollments?contractId=' + contractId
 
To:
        create_enrollment_url = 'https://' + self.access_hostname + \
            '/cps/v2/enrollments?contractId=' + contractId + '&allow-duplicate-cn=true'

**Comment by vreddhi** [comment]
New version 1.0.6 has the enhancement implemented.
