### ISSUE TITLE
Unable to Execute Package Manager on Windows Machine

### ISSUE THREAD

**Issue by rodrigoscorsatto** [akamai/cli-cps#24]
C:\Docs\ACS\Scripts\Certificates\Akamai-SSL-Expiration-Audit-master>akamai install cps
                                                                             Attempting to fetch command from https://github.com/akamai/cli-cps.git...... [OK]
               Installing...... [FAIL]
Unable to execute package manager (pip).

C:\Docs\ACS\Scripts\Certificates\Akamai-SSL-Expiration-Audit-master>AKAMAI_LOG=trace akamai install cps
'AKAMAI_LOG' is not recognized as an internal or external command,
operable program or batch file.

Software Versions:
Python 3.8.0
Node.js v12.13.0

**Comment by vreddhi** [comment]
AKAMAI_LOG=trace is an environment variable that need to be set at OS level. In windows use the set command. Ref: https://ss64.com/nt/set.html

The installation can fail due to various reasons. we need to see what specifically is causing this.

**Comment by rodrigoscorsatto** [comment]
Below is the PIP version:
 pip 19.3.1 from c:\users\rodrigo_scorsatto\appdata\local\programs\python\python38\lib\site-packages\pip (python 3.8)

Regarding the comments on my ticket, I need to know where (which path) this environment variable should be set, can it be on any directory or should be configured in some specific one? 

AKAMAI_LOG=”PATH?”

**Comment by rodrigoscorsatto** [comment]
here is the error, now with variable set to debug

C:\Docs\ACS\Scripts\Certificates\Akamai-SSL-Expiration-Audit-master>akamai install cps
Attempting to fetch command from https://github.com/akamai/cli-cps.git...
Attempting to fetch command from https://github.com/akamai/cli-cps.git...... [[32mOK[0m]

Installing...
time="2019-11-12T14:46:34-03:00" level=info msg="requirements.txt found, running pip package manager"
time="2019-11-12T14:47:22-03:00" level=debug msg="Unable execute package manager (PYTHONUSERBASE=C:\\Users\\rodrigo_scorsatto\\.akamai-cli\\src\\cli-cps C:\\Users\\rodrigo_scorsatto\\AppData\\Local\\Programs\\Python\\Python38\\Scripts\\pip3.exe install --user --ignore-installed -r requirements.txt): "
time="2019-11-12T14:47:22-03:00" level=debug msg=" ERROR: httpie 1.0.3 has requirement requests>=2.21.0, but you'll have requests 2.14.2 which is incompatible.\r"
time="2019-11-12T14:47:22-03:00" level=debug msg="    ERROR: Command errored out with exit status 1:\r"
time="2019-11-12T14:47:22-03:00" level=debug msg="     command: 'c:\\users\\rodrigo_scorsatto\\appdata\\local\\programs\\python\\python38\\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\rodrigo_scorsatto\\\\AppData\\\\Local\\\\Temp\\\\pip-install-li6vdshg\\\\cryptography\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\rodrigo_scorsatto\\\\AppData\\\\Local\\\\Temp\\\\pip-install-li6vdshg\\\\cryptography\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' install --record 'C:\\Users\\rodrigo_scorsatto\\AppData\\Local\\Temp\\pip-record-k5bovs57\\install-record.txt' --single-version-externally-managed --compile --user --prefix=\r"
time="2019-11-12T14:47:22-03:00" level=debug msg="         cwd: C:\\Users\\rodrigo_scorsatto\\AppData\\Local\\Temp\\pip-install-li6vdshg\\cryptography\\\r"
time="2019-11-12T14:47:22-03:00" level=debug msg="    Complete output (103 lines):\r"
time="2019-11-12T14:47:22-03:00" level=debug msg="    running install\r"
time="2019-11-12T14:47:22-03:00" level=debug msg="    running build\r"
time="2019-11-12T14:47:22-03:00" level=debug msg="    running build_py\r"
time="2019-11-12T14:47:22-03:00" level=debug msg="    creating build\r"
time="2019-11-12T14:47:23-03:00" level=debug msg="    creating build\\lib.win-amd64-3.8\r"
time="2019-11-12T14:47:23-03:00" level=debug msg="    creating build\\lib.win-amd64-3.8\\cryptography\r"
time="2019-11-12T14:47:23-03:00" level=debug msg="    copying src\\cryptography\\exceptions.py -> build\\lib.win-amd64-3.8\\cryptography\r"
time="2019-11-12T14:47:23-03:00" level=debug msg="    copying src\\cryptography\\fernet.py -> build\\lib.win-amd64-3.8\\cryptography\r"
time="2019-11-12T14:47:23-03:00" level=debug msg="    copying src\\cryptography\\utils.py -> build\\lib.win-amd64-3.8\\cryptography\r"
time="2019-11-12T14:47:23-03:00" level=debug msg="    copying src\\cryptography\\__about__.py -> build\\lib.win-amd64-3.8\\cryptography\r"
time="2019-11-12T14:47:23-03:00" level=debug msg="    copying src\\cryptography\\__init__.py -> build\\lib.win-amd64-3.8\\cryptography\r"
time="2019-11-12T14:47:23-03:00" level=debug msg="    creating build\\lib.win-amd64-3.8\\cryptography\\hazmat\r"
time="2019-11-12T14:47:23-03:00" level=debug msg="    copying src\\cryptography\\hazmat\\__init__.py -> build\\lib.win-amd64-3.8\\cryptography\\hazmat\r"
time="2019-11-12T14:47:23-03:00" level=debug msg="    creating build\\lib.win-amd64-3.8\\cryptography\\x509\r"
time="2019-11-12T14:47:23-03:00" level=debug msg="    copying src\\cryptography\\x509\\base.py -> build\\lib.win-amd64-3.8\\cryptography\\x509\r"
time="2019-11-12T14:47:23-03:00" level=debug msg="    copying src\\cryptography\\x509\\certificate_transparency.py -> build\\lib.win-amd64-3.8\\cryptography\\x509\r"
time="2019-11-12T14:47:23-03:00" level=debug msg="    copying src\\cryptography\\x509\\extensions.py -> build\\lib.win-amd64-3.8\\cryptography\\x509\r"
time="2019-11-12T14:47:23-03:00" level=debug msg="    copying src\\cryptography\\x509\\general_name.py -> build\\lib.win-amd64-3.8\\cryptography\\x509\r"
time="2019-11-12T14:47:23-03:00" level=debug msg="    copying src\\cryptography\\x509\\name.py -> build\\lib.win-amd64-3.8\\cryptography\\x509\r"
time="2019-11-12T14:47:23-03:00" level=debug msg="    copying src\\cryptography\\x509\\oid.py -> build\\lib.win-amd64-3.8\\cryptography\\x509\r"
time="2019-11-12T14:47:23-03:00" level=debug msg="    copying src\\cryptography\\x509\\__init__.py -> build\\lib.win-amd64-3.8\\cryptography\\x509\r"
time="2019-11-12T14:47:23-03:00" level=debug msg="    creating build\\lib.win-amd64-3.8\\cryptography\\hazmat\\backends\r"
time="2019-11-12T14:47:23-03:00" level=debug msg="    copying src\\cryptography\\hazmat\\backends\\interfaces.py -> build\\lib.win-amd64-3.8\\cryptography\\hazmat\\backends\r"
time="2019-11-12T14:47:23-03:00" level=debug msg="    copying src\\cryptography\\hazmat\\backends\\__init__.py -> build\\lib.win-amd64-3.8\\cryptography\\hazmat\\backends\r"
time="2019-11-12T14:47:23-03:00" level=debug msg="    creating build\\lib.win-amd64-3.8\\cryptography\\hazmat\\bindings\r"
time="2019-11-12T14:47:23-03:00" level=debug msg="    copying src\\cryptography\\hazmat\\bindings\\__init__.py -> build\\lib.win-amd64-3.8\\cryptography\\hazmat\\bindings\r"
time="2019-11-12T14:47:23-03:00" level=debug msg="    creating build\\lib.win-amd64-3.8\\cryptography\\hazmat\\primitives\r"
time="2019-11-12T14:47:23-03:00" level=debug msg="    copying src\\cryptography\\hazmat\\primitives\\cmac.py -> build\\lib.win-amd64-3.8\\cryptography\\hazmat\\primitives\r"
time="2019-11-12T14:47:23-03:00" level=debug msg="    copying src\\cryptography\\hazmat\\primitives\\constant_time.py -> build\\lib.win-amd64-3.8\\cryptography\\hazmat\\primitives\r"
time="2019-11-12T14:47:23-03:00" level=debug msg="    copying src\\cryptography\\hazmat\\primitives\\hashes.py -> build\\lib.win-amd64-3.8\\cryptography\\hazmat\\primitives\r"
time="2019-11-12T14:47:23-03:00" level=debug msg="    copying src\\cryptography\\hazmat\\primitives\\hmac.py -> build\\lib.win-amd64-3.8\\cryptography\\hazmat\\primitives\r"
time="2019-11-12T14:47:23-03:00" level=debug msg="    copying src\\cryptography\\hazmat\\primitives\\keywrap.py -> build\\lib.win-amd64-3.8\\cryptography\\hazmat\\primitives\r"
time="2019-11-12T14:47:23-03:00" level=debug msg="    copying src\\cryptography\\hazmat\\primitives\\mac.py -> build\\lib.win-amd64-3.8\\cryptography\\hazmat\\primitives\r"
time="2019-11-12T14:47:23-03:00" level=debug msg="    copying src\\cryptography\\hazmat\\primitives\\padding.py -> build\\lib.win-amd64-3.8\\cryptography\\hazmat\\primitives\r"
time="2019-11-12T14:47:23-03:00" level=debug msg="    copying src\\cryptography\\hazmat\\primitives\\serialization.py -> build\\lib.win-amd64-3.8\\cryptography\\hazmat\\primitives\r"
time="2019-11-12T14:47:23-03:00" level=debug msg="    copying src\\cryptography\\hazmat\\primitives\\__init__.py -> build\\lib.win-amd64-3.8\\cryptography\\hazmat\\primitives\r"
time="2019-11-12T14:47:23-03:00" level=debug msg="    creating build\\lib.win-amd64-3.8\\cryptography\\hazmat\\backends\\openssl\r"
time="2019-11-12T14:47:23-03:00" level=debug msg="    copying src\\cryptography\\hazmat\\backends\\openssl\\aead.py -> build\\lib.win-amd64-3.8\\cryptography\\hazmat\\backends\\openssl\r"
time="2019-11-12T14:47:23-03:00" level=debug msg="    copying src\\cryptography\\hazmat\\backends\\openssl\\backend.py -> build\\lib.win-amd64-3.8\\cryptography\\hazmat\\backends\\openssl\r"
time="2019-11-12T14:47:23-03:00" level=debug msg="    copying src\\cryptography\\hazmat\\backends\\openssl\\ciphers.py -> build\\lib.win-amd64-3.8\\cryptography\\hazmat\\backends\\openssl\r"
time="2019-11-12T14:47:23-03:00" level=debug msg="    copying src\\cryptography\\hazmat\\backends\\openssl\\cmac.py -> build\\lib.win-amd64-3.8\\cryptography\\hazmat\\backends\\openssl\r"
time="2019-11-12T14:47:23-03:00" level=debug msg="    copying src\\cryptography\\hazmat\\backends\\openssl\\decode_asn1.py -> build\\lib.win-amd64-3.8\\cryptography\\hazmat\\backends\\openssl\r"
time="2019-11-12T14:47:23-03:00" level=debug msg="    copying src\\cryptography\\hazmat\\backends\\openssl\\dh.py -> build\\lib.win-amd64-3.8\\cryptography\\hazmat\\backends\\openssl\r"
time="2019-11-12T14:47:23-03:00" level=debug msg="    copying src\\cryptography\\hazmat\\backends\\openssl\\dsa.py -> build\\lib.win-amd64-3.8\\cryptography\\hazmat\\backends\\openssl\r"
time="2019-11-12T14:47:23-03:00" level=debug msg="    copying src\\cryptography\\hazmat\\backends\\openssl\\ec.py -> build\\lib.win-amd64-3.8\\cryptography\\hazmat\\backends\\openssl\r"
time="2019-11-12T14:47:23-03:00" level=debug msg="    copying src\\cryptography\\hazmat\\backends\\openssl\\encode_asn1.py -> build\\lib.win-amd64-3.8\\cryptography\\hazmat\\backends\\openssl\r"
time="2019-11-12T14:47:23-03:00" level=debug msg="    copying src\\cryptography\\hazmat\\backends\\openssl\\hashes.py -> build\\lib.win-amd64-3.8\\cryptography\\hazmat\\backends\\openssl\r"
time="2019-11-12T14:47:23-03:00" level=debug msg="    copying src\\cryptography\\hazmat\\backends\\openssl\\hmac.py -> build\\lib.win-amd64-3.8\\cryptography\\hazmat\\backends\\openssl\r"
time="2019-11-12T14:47:23-03:00" level=debug msg="    copying src\\cryptography\\hazmat\\backends\\openssl\\rsa.py -> build\\lib.win-amd64-3.8\\cryptography\\hazmat\\backends\\openssl\r"
time="2019-11-12T14:47:23-03:00" level=debug msg="    copying src\\cryptography\\hazmat\\backends\\openssl\\utils.py -> build\\lib.win-amd64-3.8\\cryptography\\hazmat\\backends\\openssl\r"
time="2019-11-12T14:47:23-03:00" level=debug msg="    copying src\\cryptography\\hazmat\\backends\\openssl\\x25519.py -> build\\lib.win-amd64-3.8\\cryptography\\hazmat\\backends\\openssl\r"
time="2019-11-12T14:47:23-03:00" level=debug msg="    copying src\\cryptography\\hazmat\\backends\\openssl\\x509.py -> build\\lib.win-amd64-3.8\\cryptography\\hazmat\\backends\\openssl\r"
time="2019-11-12T14:47:23-03:00" level=debug msg="    copying src\\cryptography\\hazmat\\backends\\openssl\\__init__.py -> build\\lib.win-amd64-3.8\\cryptography\\hazmat\\backends\\openssl\r"
time="2019-11-12T14:47:23-03:00" level=debug msg="    creating build\\lib.win-amd64-3.8\\cryptography\\hazmat\\bindings\\openssl\r"
time="2019-11-12T14:47:23-03:00" level=debug msg="    copying src\\cryptography\\hazmat\\bindings\\openssl\\binding.py -> build\\lib.win-amd64-3.8\\cryptography\\hazmat\\bindings\\openssl\r"
time="2019-11-12T14:47:23-03:00" level=debug msg="    copying src\\cryptography\\hazmat\\bindings\\openssl\\_conditional.py -> build\\lib.win-amd64-3.8\\cryptography\\hazmat\\bindings\\openssl\r"
time="2019-11-12T14:47:23-03:00" level=debug msg="    copying src\\cryptography\\hazmat\\bindings\\openssl\\__init__.py -> build\\lib.win-amd64-3.8\\cryptography\\hazmat\\bindings\\openssl\r"
time="2019-11-12T14:47:23-03:00" level=debug msg="    creating build\\lib.win-amd64-3.8\\cryptography\\hazmat\\primitives\\asymmetric\r"
time="2019-11-12T14:47:23-03:00" level=debug msg="    copying src\\cryptography\\hazmat\\primitives\\asymmetric\\dh.py -> build\\lib.win-amd64-3.8\\cryptography\\hazmat\\primitives\\asymmetric\r"
time="2019-11-12T14:47:23-03:00" level=debug msg="    copying src\\cryptography\\hazmat\\primitives\\asymmetric\\dsa.py -> build\\lib.win-amd64-3.8\\cryptography\\hazmat\\primitives\\asymmetric\r"
time="2019-11-12T14:47:23-03:00" level=debug msg="    copying src\\cryptography\\hazmat\\primitives\\asymmetric\\ec.py -> build\\lib.win-amd64-3.8\\cryptography\\hazmat\\primitives\\asymmetric\r"
time="2019-11-12T14:47:23-03:00" level=debug msg="    copying src\\cryptography\\hazmat\\primitives\\asymmetric\\padding.py -> build\\lib.win-amd64-3.8\\cryptography\\hazmat\\primitives\\asymmetric\r"
time="2019-11-12T14:47:23-03:00" level=debug msg="    copying src\\cryptography\\hazmat\\primitives\\asymmetric\\rsa.py -> build\\lib.win-amd64-3.8\\cryptography\\hazmat\\primitives\\asymmetric\r"
time="2019-11-12T14:47:23-03:00" level=debug msg="    copying src\\cryptography\\hazmat\\primitives\\asymmetric\\utils.py -> build\\lib.win-amd64-3.8\\cryptography\\hazmat\\primitives\\asymmetric\r"
time="2019-11-12T14:47:23-03:00" level=debug msg="    copying src\\cryptography\\hazmat\\primitives\\asymmetric\\x25519.py -> build\\lib.win-amd64-3.8\\cryptography\\hazmat\\primitives\\asymmetric\r"
time="2019-11-12T14:47:24-03:00" level=debug msg="    copying src\\cryptography\\hazmat\\primitives\\asymmetric\\__init__.py -> build\\lib.win-amd64-3.8\\cryptography\\hazmat\\primitives\\asymmetric\r"
time="2019-11-12T14:47:24-03:00" level=debug msg="    creating build\\lib.win-amd64-3.8\\cryptography\\hazmat\\primitives\\ciphers\r"
time="2019-11-12T14:47:24-03:00" level=debug msg="    copying src\\cryptography\\hazmat\\primitives\\ciphers\\aead.py -> build\\lib.win-amd64-3.8\\cryptography\\hazmat\\primitives\\ciphers\r"
time="2019-11-12T14:47:24-03:00" level=debug msg="    copying src\\cryptography\\hazmat\\primitives\\ciphers\\algorithms.py -> build\\lib.win-amd64-3.8\\cryptography\\hazmat\\primitives\\ciphers\r"
time="2019-11-12T14:47:24-03:00" level=debug msg="    copying src\\cryptography\\hazmat\\primitives\\ciphers\\base.py -> build\\lib.win-amd64-3.8\\cryptography\\hazmat\\primitives\\ciphers\r"
time="2019-11-12T14:47:24-03:00" level=debug msg="    copying src\\cryptography\\hazmat\\primitives\\ciphers\\modes.py -> build\\lib.win-amd64-3.8\\cryptography\\hazmat\\primitives\\ciphers\r"
time="2019-11-12T14:47:24-03:00" level=debug msg="    copying src\\cryptography\\hazmat\\primitives\\ciphers\\__init__.py -> build\\lib.win-amd64-3.8\\cryptography\\hazmat\\primitives\\ciphers\r"
time="2019-11-12T14:47:24-03:00" level=debug msg="    creating build\\lib.win-amd64-3.8\\cryptography\\hazmat\\primitives\\kdf\r"
time="2019-11-12T14:47:24-03:00" level=debug msg="    copying src\\cryptography\\hazmat\\primitives\\kdf\\concatkdf.py -> build\\lib.win-amd64-3.8\\cryptography\\hazmat\\primitives\\kdf\r"
time="2019-11-12T14:47:24-03:00" level=debug msg="    copying src\\cryptography\\hazmat\\primitives\\kdf\\hkdf.py -> build\\lib.win-amd64-3.8\\cryptography\\hazmat\\primitives\\kdf\r"
time="2019-11-12T14:47:24-03:00" level=debug msg="    copying src\\cryptography\\hazmat\\primitives\\kdf\\kbkdf.py -> build\\lib.win-amd64-3.8\\cryptography\\hazmat\\primitives\\kdf\r"
time="2019-11-12T14:47:24-03:00" level=debug msg="    copying src\\cryptography\\hazmat\\primitives\\kdf\\pbkdf2.py -> build\\lib.win-amd64-3.8\\cryptography\\hazmat\\primitives\\kdf\r"
time="2019-11-12T14:47:24-03:00" level=debug msg="    copying src\\cryptography\\hazmat\\primitives\\kdf\\scrypt.py -> build\\lib.win-amd64-3.8\\cryptography\\hazmat\\primitives\\kdf\r"
time="2019-11-12T14:47:24-03:00" level=debug msg="    copying src\\cryptography\\hazmat\\primitives\\kdf\\x963kdf.py -> build\\lib.win-amd64-3.8\\cryptography\\hazmat\\primitives\\kdf\r"
time="2019-11-12T14:47:24-03:00" level=debug msg="    copying src\\cryptography\\hazmat\\primitives\\kdf\\__init__.py -> build\\lib.win-amd64-3.8\\cryptography\\hazmat\\primitives\\kdf\r"
time="2019-11-12T14:47:24-03:00" level=debug msg="    creating build\\lib.win-amd64-3.8\\cryptography\\hazmat\\primitives\\twofactor\r"
time="2019-11-12T14:47:24-03:00" level=debug msg="    copying src\\cryptography\\hazmat\\primitives\\twofactor\\hotp.py -> build\\lib.win-amd64-3.8\\cryptography\\hazmat\\primitives\\twofactor\r"
time="2019-11-12T14:47:24-03:00" level=debug msg="    copying src\\cryptography\\hazmat\\primitives\\twofactor\\totp.py -> build\\lib.win-amd64-3.8\\cryptography\\hazmat\\primitives\\twofactor\r"
time="2019-11-12T14:47:24-03:00" level=debug msg="    copying src\\cryptography\\hazmat\\primitives\\twofactor\\utils.py -> build\\lib.win-amd64-3.8\\cryptography\\hazmat\\primitives\\twofactor\r"
time="2019-11-12T14:47:24-03:00" level=debug msg="    copying src\\cryptography\\hazmat\\primitives\\twofactor\\__init__.py -> build\\lib.win-amd64-3.8\\cryptography\\hazmat\\primitives\\twofactor\r"
time="2019-11-12T14:47:24-03:00" level=debug msg="    running egg_info\r"
time="2019-11-12T14:47:24-03:00" level=debug msg="    writing src\\cryptography.egg-info\\PKG-INFO\r"
time="2019-11-12T14:47:24-03:00" level=debug msg="    writing dependency_links to src\\cryptography.egg-info\\dependency_links.txt\r"
time="2019-11-12T14:47:24-03:00" level=debug msg="    writing requirements to src\\cryptography.egg-info\\requires.txt\r"
time="2019-11-12T14:47:24-03:00" level=debug msg="    writing top-level names to src\\cryptography.egg-info\\top_level.txt\r"
time="2019-11-12T14:47:24-03:00" level=debug msg="    reading manifest file 'src\\cryptography.egg-info\\SOURCES.txt'\r"
time="2019-11-12T14:47:24-03:00" level=debug msg="    reading manifest template 'MANIFEST.in'\r"
time="2019-11-12T14:47:24-03:00" level=debug msg="    no previously-included directories found matching 'docs\\_build'\r"
time="2019-11-12T14:47:24-03:00" level=debug msg="    warning: no previously-included files matching '*' found under directory 'vectors'\r"
time="2019-11-12T14:47:24-03:00" level=debug msg="    writing manifest file 'src\\cryptography.egg-info\\SOURCES.txt'\r"
time="2019-11-12T14:47:24-03:00" level=debug msg="    running build_ext\r"
time="2019-11-12T14:47:24-03:00" level=debug msg="    generating cffi module 'build\\\\temp.win-amd64-3.8\\\\Release\\\\_padding.c'\r"
time="2019-11-12T14:47:24-03:00" level=debug msg="    creating build\\temp.win-amd64-3.8\r"
time="2019-11-12T14:47:24-03:00" level=debug msg="    creating build\\temp.win-amd64-3.8\\Release\r"
time="2019-11-12T14:47:24-03:00" level=debug msg="    generating cffi module 'build\\\\temp.win-amd64-3.8\\\\Release\\\\_constant_time.c'\r"
time="2019-11-12T14:47:24-03:00" level=debug msg="    generating cffi module 'build\\\\temp.win-amd64-3.8\\\\Release\\\\_openssl.c'\r"
time="2019-11-12T14:47:24-03:00" level=debug msg="    building '_openssl' extension\r"
time="2019-11-12T14:47:24-03:00" level=debug msg="    error: Microsoft Visual C++ 14.0 is required. Get it with \"Microsoft Visual C++ Build Tools\": https://visualstudio.microsoft.com/downloads/\r"
time="2019-11-12T14:47:24-03:00" level=debug msg="    ----------------------------------------\r"
time="2019-11-12T14:47:24-03:00" level=debug msg="ERROR: Command errored out with exit status 1: 'c:\\users\\rodrigo_scorsatto\\appdata\\local\\programs\\python\\python38\\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'C:\\\\Users\\\\rodrigo_scorsatto\\\\AppData\\\\Local\\\\Temp\\\\pip-install-li6vdshg\\\\cryptography\\\\setup.py'\"'\"'; __file__='\"'\"'C:\\\\Users\\\\rodrigo_scorsatto\\\\AppData\\\\Local\\\\Temp\\\\pip-install-li6vdshg\\\\cryptography\\\\setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' install --record 'C:\\Users\\rodrigo_scorsatto\\AppData\\Local\\Temp\\pip-record-k5bovs57\\install-record.txt' --single-version-externally-managed --compile --user --prefix= Check the logs for full command output.\r"
Installing...... [[31mFAIL[0m]

Unable to execute package manager (pip).

**Comment by roymartinezblanco** [comment]
Hi Rodrigo, 

it Seems you need this https://visualstudio.microsoft.com/visual-cpp-build-tools/ to continue

**Comment by vreddhi** [comment]
@rodrigoscorsatto were you able to get this working?

**Comment by rodrigoscorsatto** [comment]
yes, after multiple attempts I was able to make it work. 

I had several dependencies pending to install, like openssl (had a lot of issues with windows). visual studio tools, node.js, etc. 

what made a huge difference to understand why it was failing was add the AKAMAI_LOG=debug on the environment variables. so I could understand it better from the logs why it was failing. 

thanks for the support!

**Comment by vreddhi** [comment]
Glad it was resolved.
