### ISSUE TITLE
Feature Req: Section Selector

### ISSUE THREAD

**Issue by mschiessl** [akamai/cli-cps#36]
To align with the other akamai-cli integrations it would make sense to support the section selector
ie. available in the property manager module (pm)

``` 
-s, --section <section>               Section name representing Client ID in .edgerc file, defaults to "credentials"
```

Actually there has to be a "cps" section within the edgerc credentials file. 
rather than having this one, i'd prefer to only have a default section and "point" cps towards it.

**Comment by vreddhi** [comment]
The -s selector is a mechanism available to over-ride. As the readme outlines, the `cps` is the default section we look for, but you definitely can over-ride that with -s or --section.
