### ISSUE TITLE
DXE-1888 Update .edgerc default from cps to default

### ISSUE THREAD

**Issue by securitylevelup** [akamai/cli-cps#43]
Currently the CPS CLI package is accepting a default value of cps section in your .edgerc file. Can this be updated to 'default'? This is creating additional overhead for anyone to create a standalone cps block and can be confusing for those unaware that .edgerc files work with multiple sections/blocks.

Other CLI packages all use default, but CPS always throws me off and I have to supply --section default for it.

Thanks in advance!

**Comment by lkowalsk-akamai-com** [comment]
Hi @securitylevelup, we've cheanged the default section as suggestedin 2.0.0. You can check it out now.
