### ISSUE TITLE
DXE-1103 bug report env variable AKAMAI_EDGERC_ACCOUNT_KEY

### ISSUE THREAD

**Issue by porkchop8888** [akamai/cli-cps#48]
The AKAMAI_EDGERC_ACCOUNT_KEY shell environment variable was recognized but transformed into the wrong argument.  

The correct one should be "account-key".  It's missing the hyphen.

$ export AKAMAI_EDGERC_ACCOUNT_KEY=F-AC-1234567
$ akamai cps list
usage: akamai cps [--version]  ...
akamai cps: error: unrecognized arguments: --accountkey F-AC-1234567

**Comment by wzagrajcz** [comment]
Hello,
Thank You for spotting the issue. We will take care of it.

Regards,
Wojciech

**Comment by lkowalsk-akamai-com** [comment]
This issue was fixed in recent (2.0.0) release. Please check it out.
