### ISSUE TITLE
Unable to perform Audit on enrollments.

### ISSUE THREAD

**Issue by amrraj** [akamai/cli-cps#5]
Not able to run audit command for CPS enrollments. Below is the error encountered:
_Generating CPS audit file...
Processing 1 of 76: Common Name (CN): pub.**********.com
Processing 2 of 76: Common Name (CN): www.**********.com
Processing 3 of 76: Common Name (CN): www.**********.com
Traceback (most recent call last):
  File "/Users/amrraj/.akamai-cli/src/cli-cps/bin/akamai-cps", line 1293, in <module>
    status = cli()
  File "/Users/amrraj/.akamai-cli/src/cli-cps/bin/akamai-cps", line 222, in cli
    return getattr(sys.modules[__name__], args.command.replace("-", "_"))(args)
  File "/Users/amrraj/.akamai-cli/src/cli-cps/bin/akamai-cps", line 749, in audit
    + '\n')
TypeError: must be str, not NoneType_

What am I missing here?

**Comment by amrraj** [comment]
Already reported, duplicate.Closing it.

**Comment by vreddhi** [comment]
This is not a duplicate issue.

**Comment by vreddhi** [comment]
Issue is now fixed, verified and released. https://github.com/akamai/cli-cps/releases/tag/v0.1.3

**Comment by amrraj** [comment]
Thanks Vreddhi. It's working now.
